(function(CF,$){
	
	window.UIList=[
		UI_LIB_PATH+'widget.js',
		UI_LIB_PATH+'mask.js',
		UI_LIB_PATH+'calendar.js',
		UI_LIB_PATH+'datepicker.js',
		UI_LIB_PATH+'form.js',
		UI_LIB_PATH+'form/text.js',
		UI_LIB_PATH+'form/textarea.js',
		UI_LIB_PATH+'form/color.js',
		UI_LIB_PATH+'form/combo.js',
		UI_LIB_PATH+'form/date.js',
		UI_LIB_PATH+'form/radio.js',
		UI_LIB_PATH+'form/checkbox.js',
		UI_LIB_PATH+'form/vtypes.js',
		UI_LIB_PATH+'button.js',
		UI_LIB_PATH+'menu.js',
		UI_LIB_PATH+'splitbutton.js',
		UI_LIB_PATH+'toolbar.js',
		UI_LIB_PATH+'tab.js',
		UI_LIB_PATH+'window.js',
		UI_LIB_PATH+'colorpicker.js',
		UI_LIB_PATH+'undo.js',
		UI_LIB_PATH+'quicktip.js',
		UI_LIB_PATH+'dragdrop.js',
		UI_LIB_PATH+'tree.js'
	];

})();
